apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumerdeploy
  namespace: default
  labels:
    app: consumerdeploy
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumerdeploy
  strategy:
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: consumerdeploy   
    spec:
      containers:
      - name: consumerdeploy
        image: cr1wxpoc.azurecr.io/consumer:v2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi 
