apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisherdeploy
  namespace: default
  labels:
    app: publisherdeploy
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisherdeploy
  strategy:
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: publisherdeploy   
    spec:
      containers:
      - name: publisherdeploy
        image: cr1wxpoc.azurecr.io/publisher:v3
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi 